# Generated by Django 4.1 on 2023-02-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=264)),
                ('phone_number', models.CharField(max_length=264)),
                ('email', models.CharField(max_length=264)),
                ('subject', models.CharField(max_length=264)),
                ('message', models.CharField(max_length=464)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128, null=True)),
                ('img_url', models.ImageField(default='images/default.jpg', null=True, upload_to='images/')),
                ('date', models.DateField(null=True)),
                ('url', models.URLField(max_length=128, null=True)),
                ('status', models.CharField(max_length=264, null=True, unique=True)),
            ],
        ),
    ]
